version: '2'
services:
  zerotier:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  wireguard:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  httpd:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./httpd:/app
  ftpd:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./ftpd:/app
  rosnode:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./rosnode:/app
  mongodb:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./mongodb:/app
  vehicle:
    # Need extra cpu resources to run the h264 encoder sockets.
    cpuset: "1,4,5"
    build:
      context: .
      dockerfile: vehicles/carla09/Dockerfile
    image: centipede2donald/byodr-ce:carla-099
    restart: 'no'
    network_mode: host
    volumes:
      - ./common:/common
      - ./vehicles/carla09:/app
  teleop:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./teleop:/app
  pilot:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./pilot:/app
  inference:
    build:
      context: .
      dockerfile: inference/runtime-cp36-x86.dockerfile
    image: centipede2donald/byodr-ce:inference-carla
    restart: 'no'
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./common:/common
      - ./inference:/app
