version: '2'
services:
  zerotier:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  httpd:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  ftpd:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  rosnode:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  raspi:
    build:
      context: .
      dockerfile: raspi/Dockerfile
    image: centipede2donald/byodr-ce:servos
    user: root
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./raspi:/app
  vehicle:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests_rover.py"]
    volumes:
      - ./common:/common
      - ./vehicles/rover:/app
  teleop:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./teleop:/app
  pilot:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./pilot:/app
  inference:
    restart: 'no'
    command: ["python3", "-m", "pytest", "-vvv", "inference/tests.py"]
    volumes:
      - ./common:/common
      - ./inference:/app
