version: '2'
services:
  teleop:
    build:
      context: ..
      dockerfile: teleop/Dockerfile
    image: centipede2donald/byodr-ce:teleop
    container_name: byodr_teleop
    ports:
      - "80:9100"
    volumes:
      - ${DC_CONFIG_DIR}:/config
  pilot:
    build:
      context: ..
      dockerfile: pilot/Dockerfile
    image: centipede2donald/byodr-ce:pilot
    container_name: byodr_pilot
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw
  recorder:
    build:
      context: ..
      dockerfile: recorder/Dockerfile
    image: centipede2donald/byodr-ce:recorder
    container_name: byodr_recorder
    volumes:
      - ${DC_CONFIG_DIR}:/config
      - ${DC_RECORDER_SESSIONS}:/sessions
    volumes_from:
      - teleop:rw
  vehicle:
    build:
      context: ..
    image: rwgrim/docker-noop:latest
    container_name: byodr_vehicle
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw
  inference:
    build:
      context: ..
    image: rwgrim/docker-noop:latest
    container_name: byodr_inference
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw


