version: '2'
volumes:
  volume_zerotier_config:
  volume_local_config:
services:
  pigpiod:
    image: centipede2donald/raspbian-stretch:pigpio-zmq-byodr-0.25.0
    container_name: pigpiod
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    command: bash -c "/bin/rm -rf /var/run/pigpio.pid && /pigpio/pigpiod -gl"
  zerotier:
    image: zyclonite/zerotier:1.6.6
    container_name: zerotier-one
    user: root
    restart: always
    network_mode: host
    devices:
      - '/dev/net/tun'
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - CAP_SYS_RAWIO
    volumes:
      - volume_zerotier_config:/var/lib/zerotier-one:rw
  servos:
    build:
      context: .
      dockerfile: pi_gpio.dockerfile
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
    user: root
    restart: always
    depends_on:
      - "pigpiod"
    network_mode: "host"
    command: bash -c "modprobe i2c-dev && python3 -m ras.servos --config /config/driver.ini"
    environment:
      GPIOZERO_PIN_FACTORY: 'pigpio'
    volumes:

      - volume_local_config:/config:rw
  stream0:
    build:
      context: .
      dockerfile: pi_gstreamer.dockerfile
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    command: ["python3", "-m", "stream.camera", "--port", "9101", "--config", "/config/camera0.ini"]
    stop_signal: SIGKILL
    volumes:
      - volume_local_config:/config:rw
  stream1:
    build:
      context: .
      dockerfile: pi_gstreamer.dockerfile
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    command: ["python3", "-m", "stream.camera", "--port", "9102", "--config", "/config/camera1.ini"]
    stop_signal: SIGKILL
    volumes:
      - volume_local_config:/config:rw

