version: '2'
volumes:
  volume_zerotier_config:
  volume_local_config:
services:
  zerotier:
    image: zyclonite/zerotier:1.6.6
    container_name: zerotier-one
    user: root
    restart: always
    network_mode: host
    devices:
      - '/dev/net/tun'
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - CAP_SYS_RAWIO
    volumes:
      - volume_zerotier_config:/var/lib/zerotier-one:rw
  servos:
    build:
      context: .
      dockerfile: servos/Dockerfile
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
    user: root
    restart: always
    network_mode: 'host'
    volumes:
      - volume_local_config:/config:rw
  stream0:
    build:
      context: .
      dockerfile: stream/Dockerfile
    privileged: true
    user: root
    restart: always
    network_mode: 'host'
    command: ['python3', '-m', 'stream.camera', '--port', '9101', '--config', '/config/camera0.ini']
    stop_signal: SIGKILL
    volumes:
      - volume_local_config:/config:rw
  stream1:
    build:
      context: .
      dockerfile: stream/Dockerfile
    privileged: true
    user: root
    restart: always
    network_mode: 'host'
    command: ['python3', '-m', 'stream.camera', '--port', '9102', '--config', '/config/camera1.ini']
    stop_signal: SIGKILL
    volumes:
      - volume_local_config:/config:rw
