name: Docker Compose Test

on:
  push:
    branches:
      - main
      - '*'

jobs:
  Test_Docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        include:
          - os: ubuntu-18.04
            services: zerotier, wireguard, httpd, teleop, pilot, inference
          - os: ubuntu-20.04
            services: mongodb, ftpd, rosnode, vehicle

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Docker compose build
        run: |
          services="${{ matrix.services }}"
          docker-compose -f docker-compose.yml -f docker-compose.override.yml build $(echo ${services} | tr ',' ' ')

      - name: Docker compose up
        run: |
          services="${{ matrix.services }}"
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d $(echo ${services} | tr ',' ' ')
          sleep 30
          docker-compose -f docker-compose.yml -f docker-compose.override.yml down

  Test_Pi_Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Docker compose build (raspi)
        run: docker-compose -f raspi/docker-compose.yml build

      - name: Docker compose up (raspi)
        run: |
          docker-compose -f raspi/docker-compose.yml up -d
          sleep 30
          docker-compose -f raspi/docker-compose.yml down
