name: Docker Compose Test

on:
  push:
    branches:
      - main
      - '*'

jobs:
  Nano_Docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Docker compose build
        run: |
          cd jetson_runtime
          docker-compose build

      - name: Docker compose up
        run: |
          cd jetson_runtime
          docker-compose up -d
          sleep 30
          docker-compose down

  Pi_Docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Docker compose build (raspi)
        run: |
          cd pi4_runtime
          docker-compose build

      - name: Docker compose up (raspi)
        run: |
          cd pi4_runtime
          docker-compose up -d
          sleep 30
          docker-compose down
