name: Docker Compose Test

on:
  push:
    branches:
      - main
      - '*'

jobs:
  Nano_Docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Docker compose build
        run: |
          services="zerotier wireguard httpd teleop pilot ftpd rosnode vehicle"
          docker-compose -f docker-compose.yml -f docker-compose.override.yml build $services

      - name: Docker compose up
        run: |
          services="zerotier wireguard httpd teleop pilot ftpd rosnode vehicle"
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d $services
          sleep 30
          docker-compose -f docker-compose.yml -f docker-compose.override.yml down

  Pi_Docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Docker compose build (raspi)
        run: docker-compose -f raspi/docker-compose.yml build

      - name: Docker compose up (raspi)
        run: |
          docker-compose -f raspi/docker-compose.yml up -d
          sleep 30
          docker-compose -f raspi/docker-compose.yml down
