version: '2'
services:
  inference:
    build:
      context: ./
      dockerfile: inference/Dockerfile.jp
    volumes:
      - './inference:/app'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'
  vehicle:
    privileged: true
    user: 'root'
    build:
      context: ./
      dockerfile: vehicles/exr/Dockerfile
    image: centipede2donald/byodr-ce:vehicle-exr
    volumes:
      - ./common:/common
      - ./docker/deps:/deps
      - ./vehicles/exr:/app
      - /dev/ueye:/dev/ueye
      - /dev/pcan32:/dev/pcan32
      - /dev/pcan-usb:/dev/pcan-usb
      - /dev/pcanusb32:/dev/pcanusb32
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw


